controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

graphql:
    path: /docs/graphql
    controller: api_platform.graphql.action.graphql_playground